### ISSUE TITLE
Get url of an arbitrary image not included in stylesheet/javascript

### ISSUE THREAD

**Issue by simplenotezy** [swashata/wpackio-enqueue#8]
I have found this issue related to getting a image URL from the manifest: https://github.com/swashata/wpackio-enqueue/issues/4

However, this does not work since my image is only used in the HTML (for an Admin Menu Icon), so it is not included in the manifest. Is there a way to force it to be included in the manifest?

**Comment by swashata** [comment]
As said here https://github.com/swashata/wp-webpack-script/issues/807#issuecomment-569422120 I would recommend not to reference the image at all, which isn't a part of your javascript application. For images needed from server side, like this, just use the image from what-ever location you find convenient.

**Comment by swashata** [comment]
Also, I would like to focus on the fact, that this tooling is a module bundler (webpack) optimized for specific WordPress use case. Now module bundler is primarily for JavaScript apps, that run on the front-end (at-least in case of WordPress, because the server is PHP).

So the tooling shouldn't be concerned with static assets which are not dependencies of your JavaScript entrypoint (or the app).
